apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-rollout-vsvc
  namespace: demo
spec:
  gateways:
    - istio-rollout-gateway
  hosts:
    - "frontend.localdev.me"
    # - istio-rollout.local
  http:
    # Canary header-based routing
    - name: canary-debug
      match:
        - headers:
            x-canary:
              exact: "true"
      route:
        - destination:
            host: istio-rollout-canary
          weight: 100

    # Default routing (primary)
    - name: primary
      route:
        - destination:
            host: istio-rollout-stable
          weight: 100
        - destination:
            host: istio-rollout-canary
          weight: 0
