
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: istio-success-rate
  namespace: demo
spec:
  # this analysis template requires a service name and namespace to be supplied to the query
  args:
  - name: service
  - name: namespace
  metrics:
  - name: success-rate
    initialDelay: 30s
    interval: 20s
    successCondition: result[0] > 99
    provider:
      prometheus:
        address: http://kube-prom-stack-kube-prome-prometheus.monitoring:9090
        query: |
          100 * sum(rate(istio_requests_total{destination_service="istio-rollout.demo.svc.cluster.local",response_code=~"2..", reporter="destination"}[1m])) 
          / sum(rate(istio_requests_total{destination_service="istio-rollout.demo.svc.cluster.local",reporter="destination"}[1m]))